run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gofmt

linters-settings:
  errcheck:
    exclude-functions:
      - (*go.uber.org/zap.Logger).Sync
