server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  tls:
    enabled: false

worker:
  pool_size: 4
  queue_size: 100
  timeout: 5m
  retry_count: 3
  retry_delay: 10s

print:
  max_file_size: 10485760  # 10MB
  output_directory: "./output"
  temp_directory: "./temp"
  timeout: 2m
  max_concurrent: 2

queue:
  type: "memory"
  max_retries: 3
  timeout: 30s

cache:
  type: "memory"
  ttl: 1h
  max_size: 104857600  # 100MB
  max_entries: 1000

logger:
  level: "debug"
  format: "text"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
