server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  tls:
    enabled: true
    cert_file: "/etc/ssl/certs/server.crt"
    key_file: "/etc/ssl/private/server.key"

worker:
  pool_size: 8
  queue_size: 500
  timeout: 10m
  retry_count: 5
  retry_delay: 30s

print:
  max_file_size: 52428800  # 50MB
  output_directory: "/var/lib/print-service/output"
  temp_directory: "/tmp/print-service"
  timeout: 5m
  max_concurrent: 4

queue:
  type: "redis"
  url: "redis://localhost:6379"
  max_retries: 5
  timeout: 60s

cache:
  type: "redis"
  url: "redis://localhost:6379"
  ttl: 24h
  max_size: 1073741824  # 1GB
  max_entries: 10000

logger:
  level: "info"
  format: "json"
  output: "file"
  file: "/var/log/print-service/app.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true
